-   id: alex
    name: alex
    description: ''
    entry: alex
    language: node
    exclude: ".pre-commit-config.yaml"
    'types': [text]
    args: []
    require_serial: false
    additional_dependencies: ["alex@4.0.0"]
    minimum_pre_commit_version: '0'
